name: Despliegue de Laravel

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Copiar archivo .env
        run: cp /home/jfap19952/deploy_config/.env .env

      - name: Instalar dependencias de Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Ejecutar migraciones
        run: php artisan migrate --force

      - name: Optimizar Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan optimize

      - name: Ajustar permisos
        run: |
          sudo chown -R $USER:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache